### ISSUE TITLE
[bug] Orb doesn't perform code checkout

### ISSUE THREAD

**Issue by atmosx** [CircleCI-Public/path-filtering-orb#11]
## Orb version:

v0.0.2

## What happened:

I'm using the orb v0.0.2 to perform path filtering as follows:

```
workflows:
  gameserver-config:
    jobs:
      - path-filtering/filter:
          config-path: .circleci/modules/gameserver.yml
          base-revision: staging
          mapping: |
            modules/code-game-.*
          filters:
            branches:
              only:
                - panagiotis/eng-1162-circleci-introduce-path-base-builds
```

Error I'm getting in CircleCI:

```
Traceback (most recent call last):
  File "<string>", line 10, in <module>
  File "/home/circleci/.pyenv/versions/3.8.10/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'merge-base', 'staging', 'd1f1cea2030d424011509e9bc5ebca39626134ab']' returned non-zero exit status 128.
```

## Expected behavior:

Perform path filtering

## Additional Information:

The problem is that there's no source code in the directory. The strange thing is that adding `- checkout` step doesn't solve this. I've also seen that the orb performs `checkout` anyway.

I'm probably doing something wrong, any ideas?

**Comment by atmosx** [comment]
Not sure which one was the fixed, but:

- I was missing the `setup: true` keyword in the YAML
- Had to use the `origin` keyword pointing to a branch: `base-revision: origin/staging`
