### ISSUE TITLE
Missing python3-distutils dependency

### ISSUE THREAD

**Issue by Oleksandr-Kushchak-i2** [CircleCI-Public/path-filtering-orb#81]
## Orb version:
0.1.6

## What happened:
There is a missing dependency, please see log below:
```sh
Traceback (most recent call last):
  File "circleci_get_pip.py", line 32321, in <module>
    main()
  File "circleci_get_pip.py", line 135, in main
    bootstrap(tmpdir=tmpdir)
  File "circleci_get_pip.py", line 111, in bootstrap
    monkeypatch_for_cert(tmpdir)
  File "circleci_get_pip.py", line 92, in monkeypatch_for_cert
    from pip._internal.commands.install import InstallCommand
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpx2nqnr4m/pip.zip/pip/_internal/commands/__init__.py", line 9, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpx2nqnr4m/pip.zip/pip/_internal/cli/base_command.py", line 15, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpx2nqnr4m/pip.zip/pip/_internal/cli/cmdoptions.py", line 24, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpx2nqnr4m/pip.zip/pip/_internal/cli/parser.py", line 12, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpx2nqnr4m/pip.zip/pip/_internal/configuration.py", line 26, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpx2nqnr4m/pip.zip/pip/_internal/utils/logging.py", line 29, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpx2nqnr4m/pip.zip/pip/_internal/utils/misc.py", line 44, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpx2nqnr4m/pip.zip/pip/_internal/locations/__init__.py", line 66, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/tmp/tmpx2nqnr4m/pip.zip/pip/_internal/locations/_distutils.py", line 20, in <module>
ModuleNotFoundError: No module named 'distutils.cmd'
```

Can be resolved by installing `python3-distutils` on the the executor.
```sh
sudo apt-get install python3-distutils
```

## Expected behavior:

Expected [Set parameters](https://github.com/CircleCI-Public/path-filtering-orb/blob/b433953e3c3b5444d1ded7bfba9c39288d79c9b3/src/commands/set-parameters.yml#LL33C13-L33C27) step to work out of the box on the `cimg/base:stable` image. 
Works on the `0.1.5` version out of the box.

## Additional Information:

We are using the `cimg/base:stable` for the docker executor.

**Comment by jenny-miggin** [comment]
Hi @Oleksandr-Kushchak-i2,

The `cimg/base:stable` does not contain the dependencies required for this version of the orb. The recommendation is to either use `cimg/python:3.8` as it's the default for the orb, or use the base image and install the needed dependencies.
